// <auto-generated />
namespace SharePay.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Make_Password_Optional_For_External_Logins : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Make_Password_Optional_For_External_Logins));
        
        string IMigrationMetadata.Id
        {
            get { return "201803302129059_Make_Password_Optional_For_External_Logins"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
